# Generated by Django 5.2.1 on 2025-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('specials', 'Specials'), ('hot_sandwiches', 'Hot Sandwiches'), ('cold_sandwiches', 'Cold Sandwiches'), ('plates', 'Plates'), ('sides', 'Sides'), ('breakfast', 'Breakfast')], max_length=20)),
            ],
        ),
    ]
