# Generated by Django 5.2.1 on 2025-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
